# Generated by Django 6.0.5 on 2026-06-03 05:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0002_designation_employeehierarchy_organizationposition"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("days_allowed", models.PositiveIntegerField()),
                ("requires_approval", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "leave_types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("grace_period_minutes", models.PositiveIntegerField(default=15)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "shifts",
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("is_recurring", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "holidays",
                "ordering": ["date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "date"), name="uniq_holiday_name_date"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_leaves",
                        to="employees.employeeprofile",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="employees.employeeprofile",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="attendance.leavetype",
                    ),
                ),
            ],
            options={
                "db_table": "leave_requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["employee", "status"], name="leave_emp_status_idx"
                    ),
                    models.Index(
                        fields=["start_date", "end_date"], name="leave_date_range_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("check_in", models.DateTimeField(blank=True, null=True)),
                ("check_out", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("half_day", "Half Day"),
                            ("on_leave", "On Leave"),
                        ],
                        default="present",
                        max_length=20,
                    ),
                ),
                (
                    "worked_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="employees.employeeprofile",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendances",
                        to="attendance.shift",
                    ),
                ),
            ],
            options={
                "db_table": "attendances",
                "ordering": ["-date", "employee"],
                "indexes": [
                    models.Index(fields=["date"], name="attendance_date_idx"),
                    models.Index(
                        fields=["employee", "date"], name="attendance_emp_date_idx"
                    ),
                    models.Index(fields=["status"], name="attendance_status_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee", "date"), name="uniq_employee_date"
                    )
                ],
            },
        ),
    ]
