# Generated by Django 5.1.7 on 2026-06-01 12:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("task_notifications", models.BooleanField(default=True)),
                ("project_notifications", models.BooleanField(default=True)),
                ("mention_notifications", models.BooleanField(default=True)),
                ("approval_notifications", models.BooleanField(default=True)),
                ("system_notifications", models.BooleanField(default=True)),
                ("realtime_enabled", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "notification_preferences",
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="action_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("task", "Task"),
                    ("project", "Project"),
                    ("mention", "Mention"),
                    ("approval", "Approval"),
                    ("system", "System"),
                ],
                default="system",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="target_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="notification",
            name="target_type",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["category"], name="notif_category_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["target_type", "target_id"], name="notif_target_idx"
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_preference",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
