# Generated by Django 6.0.5 on 2026-06-03 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notification_link"),
        (
            "notifications",
            "0002_notificationpreference_notification_action_url_and_more",
        ),
    ]

    operations = []
