# Generated by Django 5.1.7 on 2026-06-05 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_must_change_password_employeeonboardingtoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="must_change_password",
        ),
        migrations.DeleteModel(
            name="EmployeeOnboardingToken",
        ),
    ]
