# Generated by Django 5.1.7 on 2026-06-05 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_email_loginhistory_otpcode"),
        ("accounts", "0006_remove_user_must_change_password_and_more"),
    ]

    operations = []
