# Generated by Django 5.1.7 on 2026-06-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_merge_20260605_1544"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(default=True),
        ),
    ]
