# Generated by Django 5.1.7 on 2026-06-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_user_email_alter_user_must_change_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(default=True),
        ),
    ]
