# Generated by Django 5.1.7 on 2026-05-22 11:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Designation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=150, unique=True)),
                ("level", models.PositiveIntegerField()),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "designations",
                "ordering": ["level", "title"],
                "indexes": [
                    models.Index(fields=["level"], name="designation_level_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="EmployeeHierarchy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hierarchy_assignments",
                        to="employees.employeeprofile",
                    ),
                ),
                (
                    "reporting_manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_hierarchy_assignments",
                        to="employees.employeeprofile",
                    ),
                ),
            ],
            options={
                "db_table": "employee_hierarchies",
                "ordering": ["-effective_from"],
                "indexes": [
                    models.Index(
                        fields=["employee", "is_active"],
                        name="emp_hierarchy_active_idx",
                    ),
                    models.Index(
                        fields=["reporting_manager"], name="emp_hierarchy_mgr_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrganizationPosition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="positions",
                        to="employees.department",
                    ),
                ),
                (
                    "designation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="positions",
                        to="employees.designation",
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_position",
                        to="employees.employeeprofile",
                    ),
                ),
                (
                    "reporting_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_positions",
                        to="employees.organizationposition",
                    ),
                ),
            ],
            options={
                "db_table": "organization_positions",
                "ordering": [
                    "department__name",
                    "designation__level",
                    "employee__user__full_name",
                ],
                "indexes": [
                    models.Index(fields=["department"], name="org_position_dept_idx"),
                    models.Index(fields=["designation"], name="org_position_desig_idx"),
                ],
            },
        ),
    ]
