# Generated by Django 5.1.7 on 2026-05-31 08:31

import apps.tasks.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0002_designation_employeehierarchy_organizationposition"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=220)),
                ("description", models.TextField(blank=True)),
                ("task_code", models.CharField(max_length=60, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("backlog", "Backlog"),
                            ("todo", "To Do"),
                            ("in_progress", "In Progress"),
                            ("review", "Review"),
                            ("blocked", "Blocked"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="backlog",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "actual_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_tasks",
                        to="employees.employeeprofile",
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="projects.milestone",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_tasks",
                        to="employees.employeeprofile",
                    ),
                ),
            ],
            options={
                "db_table": "tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("status_changed", "Status Changed"),
                            ("assigned", "Assigned"),
                            ("priority_changed", "Priority Changed"),
                            ("due_date_changed", "Due Date Changed"),
                            ("commented", "Commented"),
                            ("attached", "Attached"),
                            ("checklist_updated", "Checklist Updated"),
                            ("dependency_updated", "Dependency Updated"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                            ("updated", "Updated"),
                        ],
                        max_length=40,
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_activities",
                        to="employees.employeeprofile",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "db_table": "task_activities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_assignments_made",
                        to="employees.employeeprofile",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_assignments",
                        to="employees.employeeprofile",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "db_table": "task_assignments",
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.tasks.models.task_attachment_upload_path
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="tasks.task",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="task_attachments",
                        to="employees.employeeprofile",
                    ),
                ),
            ],
            options={
                "db_table": "task_attachments",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskChecklist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklists",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "db_table": "task_checklists",
                "ordering": ["position", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskChecklistItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=220)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="tasks.taskchecklist",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_task_checklist_items",
                        to="employees.employeeprofile",
                    ),
                ),
            ],
            options={
                "db_table": "task_checklist_items",
                "ordering": ["position", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("comment", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="task_comments",
                        to="employees.employeeprofile",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="tasks.taskcomment",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "db_table": "task_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskDependency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dependency_type",
                    models.CharField(
                        choices=[
                            ("finish_to_start", "Finish to Start"),
                            ("start_to_start", "Start to Start"),
                            ("finish_to_finish", "Finish to Finish"),
                        ],
                        default="finish_to_start",
                        max_length=30,
                    ),
                ),
                (
                    "predecessor_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="successor_dependencies",
                        to="tasks.task",
                    ),
                ),
                (
                    "successor_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predecessor_dependencies",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "db_table": "task_dependencies",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["project", "status"], name="task_project_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["milestone", "status"], name="task_mstone_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["priority"], name="task_priority_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["due_date"], name="task_due_date_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["created_by"], name="task_created_by_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["is_archived"], name="task_archived_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["task_code"], name="task_code_idx"),
        ),
        migrations.AddIndex(
            model_name="taskactivity",
            index=models.Index(
                fields=["task", "created_at"], name="task_activity_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskactivity",
            index=models.Index(fields=["activity_type"], name="task_activity_type_idx"),
        ),
        migrations.AddIndex(
            model_name="taskactivity",
            index=models.Index(fields=["actor"], name="task_activity_actor_idx"),
        ),
        migrations.AddIndex(
            model_name="taskassignment",
            index=models.Index(
                fields=["task", "employee"], name="task_assign_employee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskassignment",
            index=models.Index(fields=["employee"], name="task_assign_emp_idx"),
        ),
        migrations.AddIndex(
            model_name="taskassignment",
            index=models.Index(fields=["assigned_at"], name="task_assign_at_idx"),
        ),
        migrations.AddIndex(
            model_name="taskattachment",
            index=models.Index(
                fields=["task", "uploaded_at"], name="task_attach_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskattachment",
            index=models.Index(fields=["uploaded_by"], name="task_attach_user_idx"),
        ),
        migrations.AddIndex(
            model_name="taskchecklist",
            index=models.Index(fields=["task", "position"], name="task_cl_pos_idx"),
        ),
        migrations.AddIndex(
            model_name="taskchecklistitem",
            index=models.Index(
                fields=["checklist", "position"], name="task_cli_pos_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskchecklistitem",
            index=models.Index(fields=["is_completed"], name="task_cli_completed_idx"),
        ),
        migrations.AddIndex(
            model_name="taskcomment",
            index=models.Index(
                fields=["task", "created_at"], name="task_comment_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskcomment",
            index=models.Index(fields=["author"], name="task_comment_author_idx"),
        ),
        migrations.AddIndex(
            model_name="taskcomment",
            index=models.Index(fields=["parent"], name="task_comment_parent_idx"),
        ),
        migrations.AddIndex(
            model_name="taskdependency",
            index=models.Index(
                fields=["predecessor_task"], name="task_dep_predecessor_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskdependency",
            index=models.Index(
                fields=["successor_task"], name="task_dep_successor_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="taskdependency",
            constraint=models.UniqueConstraint(
                fields=("predecessor_task", "successor_task", "dependency_type"),
                name="uniq_task_dependency",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskdependency",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("predecessor_task", models.F("successor_task")), _negated=True
                ),
                name="prevent_task_self_dependency",
            ),
        ),
    ]
