# Generated by Django 5.1.7 on 2026-06-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_organizationposition_updates"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="taskassignment",
            constraint=models.UniqueConstraint(
                fields=("task", "employee"), name="uniq_task_employee_assignment"
            ),
        ),
    ]
