# Generated by Django 6.0.5 on 2026-06-03 06:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "snapshot_type",
                    models.CharField(
                        choices=[
                            ("performance", "Employee Performance"),
                            ("productivity", "Team Productivity"),
                            ("project", "Project Progress"),
                            ("task", "Task Analytics"),
                            ("attendance", "Attendance Analytics"),
                            ("workflow", "Workflow Efficiency"),
                            ("dashboard", "Dashboard Overview"),
                        ],
                        max_length=30,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("cached_at", models.DateTimeField(auto_now=True)),
                ("ttl_seconds", models.PositiveIntegerField(default=300)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics Snapshot",
                "verbose_name_plural": "Analytics Snapshots",
                "db_table": "analytics_snapshots",
                "indexes": [
                    models.Index(
                        fields=["user", "snapshot_type", "cached_at"],
                        name="analytics_s_user_id_5e89a7_idx",
                    )
                ],
            },
        ),
    ]
